CXX = mpiicpc
CXXFLAGS = -g

TARGETS = hello mpihello sendrecv99 ring ring-time exchange1 exchange2 trapezoid_seq trapezoid_par pi_seq pi_par client-server recursive_seq nest_seq.cc nest_par.cc

all: $(TARGETS)

clean:
	/bin/rm -f $(TARGETS) *.o *~




